helm-extra-args: --timeout 300s
check-version-increment: false
charts: charts/microgateway
debug: true
namespace: default
release-label: app.kubernetes.io/instance
chart-repos:
        - bitnami=https://raw.githubusercontent.com/bitnami/charts/pre-2022/bitnami
        - ealenn=https://ealenn.github.io/charts
