helm-extra-args: --timeout 300s
check-version-increment: false
debug: true
namespace: microgateway-validation
release-label: release
chart-repos: 
        - bitnami=https://charts.bitnami.com/bitnami
