helm-extra-args: --timeout 480s
check-version-increment: false
debug: true
namespace: validation-namespace
release-label: release
chart-repos: 
        - bitnami=https://charts.bitnami.com/bitnami
        - ealenn=https://ealenn.github.io/charts
