helm-extra-args: --timeout 300s
check-version-increment: false
debug: true
namespace: default
release-label: release
chart-repos: 
        - bitnami=https://charts.bitnami.com/bitnami
        - ealenn=https://ealenn.github.io/charts
