image:
  repository:
    runtime: docker.io/ergon/airlock-microgateway-nightly
    configbuilder: docker.io/ergon/airlock-microgateway-configbuilder-nightly
  tag: 3.0.0.sprint3_Build002
  pullPolicy: Always

config:
  dsl:
    session:
      redis_hosts: [redis-master]
    apps:
      - mappings:
          - session_handling: enforce_session
            deny_rule_groups:
              - level: strict

imagePullSecrets:
  - name: "dockersecret"

hpa:
  enabled: true

redis:
  enabled: true
echo-server:
  enabled: true
ingress:
  enabled: true
