image:
  repository:
    runtime: docker.io/ergon/airlock-microgateway
    configbuilder: docker.io/ergon/airlock-microgateway-configbuilder
  tag: 2.1.0
  pullPolicy: Always

config:
  dsl:
    session:
      redis_hosts: [redis-master]
    apps:
      - mappings:
          - session_handling: enforce_session
            deny_rule_groups:
              - level: strict

hpa:
  enabled: true

redis:
  enabled: true
echo-server:
  enabled: true
ingress:
  enabled: true
