config:
  existingSecret: "microgatewaysecrets"
  dsl:
    session:
      redis_hosts: [redis-master]
    apps:
      - mappings:
          - session_handling: enforce_session
            deny_rule_groups:
              - level: strict

imagePullSecrets:
  - name: "dockersecret"
redis:
  enabled: true
echo-server:
  enabled: true
ingress:
  enabled: true
