config:
  generic:
    existingSecret: "microgatewaysecrets"
  simple:
    mapping:
      entryPath: /
      denyRules:
        enabled: true
        level: strict
        logOnly: false
imagePullSecrets:
  - name: "dockersecret"
redis:
  enabled: true
echo-server:
  enabled: true
ingress:
  enabled: true
