{{- $fullName := include "microgateway.fullname" . -}}
{{- $hpa := .Values.hpa -}}
{{- if $hpa.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $fullName }}
  labels:
      {{- include "microgateway.labels" . | nindent 4 }}
spec:
  maxReplicas: {{ $hpa.maxReplicas}}
  minReplicas: {{ $hpa.minReplicas}}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $fullName }}
  metrics:
  {{- with $hpa.resource.cpu }}
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: {{ . }}
  {{- end }}
  {{- with $hpa.resource.memory }}
  - type: Resource
    resource:
      name: memory
      targetAverageValue: {{ . }}
  {{- end }}
{{- end }}
