{{- $fullName := include "microgateway.fullname" . -}}
{{- $hpa := .Values.hpa -}}
{{- if $hpa.enabled }}
{{- if semverCompare ">=1.26-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: autoscaling/v2
{{- else -}}
apiVersion: autoscaling/v2beta2
{{- end }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $fullName }}
  labels:
      {{- include "microgateway.labels" . | nindent 4 }}
spec:
  maxReplicas: {{ $hpa.maxReplicas}}
  minReplicas: {{ $hpa.minReplicas}}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $fullName }}
  metrics:
  {{- with $hpa.resource.cpu }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ . }}
  {{- end }}
  {{- with $hpa.resource.memory }}
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: {{ . }}
  {{- end }}
{{- end }}
