{{- $ingress := .Values.ingress -}}
{{- if $ingress.enabled -}}
{{- $fullName := include "microgateway.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $numOfHosts := len $ingress.hosts -}}

{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "microgateway.labels" . | nindent 4 }}
  {{- with $ingress.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- with $ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
{{- if $ingress.tls }}
  tls:
  {{- range $ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
    {{- if eq $numOfHosts 0 }}
    - http: 
        paths:
        - path: {{ $ingress.path }}
          pathType: {{ $ingress.pathType }}
          backend:
            service:
              name: {{ $fullName }}
              port:
      {{- with $ingress.servicePortNumber }}
                number: {{ $ingress.servicePortNumber }}
      {{- end }}
      {{- with $ingress.servicePortName }}
        {{- if not $ingress.servicePortNumber }}
                name: {{ $ingress.servicePortName }}
        {{- end }}
      {{- end }}
    {{- end }}

    {{- range $ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
        - path: {{ $ingress.path }}
          pathType: {{ $ingress.pathType }}
          backend:
            service:
              name: {{ $fullName }}
              port:
      {{- with $ingress.servicePortNumber }}
                number: {{ $ingress.servicePortNumber }}
      {{- end }}
      {{- with $ingress.servicePortName }}
        {{- if not $ingress.servicePortNumber }}
                name: {{ $ingress.servicePortName }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- else -}}
    {{- range $ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
        - path: {{ $ingress.path }}
          backend:
            serviceName: {{ $fullName }}
            servicePort: {{ $ingress.targetPort }}
    {{- end }}
  {{- end }}
{{- end }}
