{{- $ingress := .Values.ingress -}}
{{- if $ingress.enabled -}}
{{- $fullName := include "microgateway.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "microgateway.labels" . | nindent 4 }}
  {{- with $ingress.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- with $ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
{{- if $ingress.tls }}
  tls:
  {{- range $ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range $ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
        - path: {{ $ingress.path }}
          backend:
            serviceName: {{ $fullName }}
            servicePort: {{ $ingress.targetPort }}
  {{- end }}
{{- end }}
