{{- if (include "microgateway.createLicenseSecret" .) }}   
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "microgateway.licenseSecretName" . }}
  labels:
    {{- include "microgateway.labels" . | nindent 4 }}
type: Opaque
data:
{{- with .Values.config.license.key }}
  license: {{ . | b64enc | quote }}
{{- end }}
{{- end }}
