{{- if not .Values.config.passphrase.useExistingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "microgateway.passphraseSecretName" . }}
  labels:
    {{- include "microgateway.labels" . | nindent 4 }}
type: Opaque
data:
{{- if .Values.config.passphrase.value }}
  passphrase: {{ .Values.config.passphrase.value | b64enc | quote }}
{{- else }}
  passphrase: {{ randAlphaNum 128 | b64enc | quote }}
{{- end }}
{{- end }}
