{{- if (include "microgateway.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "microgateway.fullname" . }}
  labels:
    {{- include "microgateway.labels" . | nindent 4 }}
type: Opaque
data:
{{- if .Values.config.passphrase }}
  passphrase: {{ .Values.config.passphrase | b64enc | quote }}
{{- else }}
  passphrase: {{ randAlphaNum 128 | b64enc | quote }}
{{- end }}
{{- with .Values.config.license }}
  license: {{ . | b64enc | quote }}
{{- end }}
{{- end }}
