apiVersion: v1
kind: Service
metadata:
  name: {{ template "microgateway.fullname" . }}
  labels:
    {{- include "microgateway.labels" . | nindent 4 }}
  {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    name: http
  - port: {{ .Values.service.tlsPort }}
    targetPort: https
    name: https
  selector:
    {{- include "microgateway.selectorLabels" . | nindent 4 }}
