apiVersion: v1
kind: Pod
metadata:
  name: {{ template "microgateway.fullname" . }}-smoketest
  labels:
    {{- include "microgateway.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args:  ['{{ include "microgateway.fullname" . }}:{{ .Values.service.port }}/']
  restartPolicy: Never
